[theme]
base = "dark"

primaryColor = "#F5C542"
backgroundColor = "#07111F"
secondaryBackgroundColor = "#101C2E"
textColor = "#F8FAFC"
linkColor = "#F5C542"
borderColor = "#D6A93A"

font = "sans-serif"

[theme.sidebar]
backgroundColor = "#081827"
secondaryBackgroundColor = "#10233A"
textColor = "#F8FAFC"